from typing import Any

RISKS: list[dict[str, Any]] = [
    # ── Security ──────────────────────────────────────────────────────────
    {
        "id": "agent_hijacking_prompt_injection",
        "name": "Agent Hijacking & Prompt Injection",
        "domain": "security",
        "principle": "Security / Invulnerable",
        "sub_dimension": "Invulnerable",
        "root_causes": [
            "Unsanitised external input",
            "Indirect prompt injection via processed data",
            "Insufficient input validation at guard node",
        ],
        "evaluation_options": ["Input sanitisation", "Restricted agent tool access", "Human gating for sensitive decisions"],
    },
    {
        "id": "tool_misuse_confused_deputy",
        "name": "Tool Misuse & Confused Deputy",
        "domain": "security",
        "principle": "Security / Invulnerable",
        "sub_dimension": "Invulnerable",
        "root_causes": [
            "Overly permissive IAM roles",
            "Failure to apply principle of least privilege",
            "Insufficient tool call scope validation",
        ],
        "evaluation_options": ["IAM permissions audit", "Principle of least privilege", "Tool call scope validation"],
    },
    {
        "id": "data_leakage",
        "name": "Data Leakage / Data Protection Breach",
        "domain": "security",
        "principle": "Security / Privacy / Confidential",
        "sub_dimension": "Confidential",
        "root_causes": [
            "Overly permissive data access",
            "Missing PII detection layer",
            "Agent surfacing raw content without filtering or redaction",
        ],
        "evaluation_options": ["IAM permissions", "Principle of least privilege", "Secrets / PII scanning"],
    },
    {
        "id": "model_extraction_evasion_attacks",
        "name": "Model Extraction / Evasion Attacks",
        "domain": "security",
        "principle": "Security / Accountable",
        "sub_dimension": "Invulnerable",
        "root_causes": [
            "Insufficient system prompt protection",
            "Absence of query rate limiting",
            "Adversarial inputs crafted to elicit model internals or bypass reasoning constraints",
        ],
        "evaluation_options": ["System prompt protection", "Rate limiting", "Adversarial input testing"],
    },
    {
        "id": "memory_data_poisoning",
        "name": "Memory & Data Poisoning",
        "domain": "security",
        "principle": "Accountable / Human and External Systems",
        "sub_dimension": "Accountable",
        "root_causes": [
            "Unvalidated writes to persistent memory",
            "Insufficient memory provenance checking",
            "Adversarial actor with write access to memory store",
        ],
        "evaluation_options": ["Information injection testing", "Memory validation gates", "Provenance logging"],
    },
    # ── Reliability ───────────────────────────────────────────────────────
    {
        "id": "system_instability",
        "name": "System Instability",
        "domain": "reliability",
        "principle": "Robustness & Reliability",
        "sub_dimension": "Consistent",
        "root_causes": ["Probabilistic model variance", "Unexpected inputs", "External tool failures"],
        "evaluation_options": ["Output comparison", "Consistency checks across N runs"],
    },
    {
        "id": "silent_failures",
        "name": "Silent Failures",
        "domain": "reliability",
        "principle": "Robustness & Reliability / Accountable",
        "sub_dimension": "Accurate",
        "root_causes": ["Hallucinations", "Factual inconsistencies", "Incomplete data"],
        "evaluation_options": ["Two-pass verification", "Human red teaming", "Hard negatives testing"],
    },
    {
        "id": "cascading_errors",
        "name": "Cascading Errors",
        "domain": "reliability",
        "principle": "Accountable",
        "sub_dimension": "Accountable",
        "root_causes": [
            "Inter-agent dependencies",
            "Lack of error handling",
            "Faulty logic in one of the agents",
        ],
        "evaluation_options": ["Output validation", "Fault injection testing", "End-to-end trace comparison"],
    },
    {
        "id": "endless_cycles_looping",
        "name": "Endless Cycles / Looping",
        "domain": "reliability",
        "principle": "Predictable / Accountable",
        "sub_dimension": "Predictable",
        "root_causes": [
            "Recursive logic",
            "Lack of termination condition",
            "Converging tool outputs",
        ],
        "evaluation_options": ["Timeouts", "Repeated-state detection", "Token usage logging"],
    },
    {
        "id": "role_specification_drift",
        "name": "Role & Specification Drift",
        "domain": "reliability",
        "principle": "Consistent",
        "sub_dimension": "Consistent",
        "root_causes": [
            "Role ambiguity in system prompts",
            "Accumulated context shifting agent behaviour",
            "Unclear task decomposition boundaries",
        ],
        "evaluation_options": ["Role constraint validation", "Trace audit against declared role specification"],
    },
    {
        "id": "reasoning_action_mismatch",
        "name": "Reasoning-Action Mismatch",
        "domain": "reliability",
        "principle": "Transparency / Robustness & Reliability",
        "sub_dimension": "Justifiable",
        "root_causes": [
            "LLM hallucination of reasoning traces",
            "Structural decoupling of reasoning from execution steps",
        ],
        "evaluation_options": ["Reasoning-action validation", "Mismatch injection testing", "Structured output verification"],
    },
    # ── Transparency & Fairness ───────────────────────────────────────────
    {
        "id": "algorithmic_bias",
        "name": "Algorithmic Bias",
        "domain": "transparency_fairness",
        "principle": "Fair and Impartial / Unbiased",
        "sub_dimension": "Unbiased",
        "root_causes": [
            "Biased training data in underlying foundation models",
            "Skewed or non-representative input samples",
            "Feedback loops amplifying initial bias",
        ],
        "evaluation_options": [
            "Fairness metrics across demographic groups",
            "Edge-case testing",
            "Transparency & explainability review",
        ],
    },
    {
        "id": "obscure_logic_black_box",
        "name": "Obscure Logic (Black Box)",
        "domain": "transparency_fairness",
        "principle": "Transparency / Auditable",
        "sub_dimension": "Auditable",
        "root_causes": [
            "Third-party model opacity",
            "Insufficient logging of intermediate reasoning steps",
            "Missing chain-of-thought capture in structured agent outputs",
        ],
        "evaluation_options": ["Subagent logging", "Cloudwatch / observability logs", "Chain-of-thought capture"],
    },
    {
        "id": "context_rot",
        "name": "Context Rot",
        "domain": "transparency_fairness",
        "principle": "Predictable",
        "sub_dimension": "Predictable",
        "root_causes": [
            "Outdated information",
            "Ambiguous or missing contextual details",
            "Conflicting data sources",
            "Context stuffing and information asymmetry",
        ],
        "evaluation_options": ["Contradiction testing", "Recency bias testing", "Information freshness checks"],
    },
    {
        "id": "goal_misalignment",
        "name": "Goal Misalignment & Poor Definition",
        "domain": "transparency_fairness",
        "principle": "Responsible / Humane",
        "sub_dimension": "Humane",
        "root_causes": [
            "Ambiguous or incomplete goal specification",
            "Absence of organisational value constraints in agent design",
            "Misalignment between task objective and stakeholder intent",
        ],
        "evaluation_options": ["Policy adherence testing", "Value constraint validation"],
    },
    # ── Accountability ────────────────────────────────────────────────────
    {
        "id": "unapproved_self_improvements",
        "name": "Unapproved Self-Improvements",
        "domain": "accountability",
        "principle": "Accountable / Resolvable",
        "sub_dimension": "Accountable",
        "root_causes": ["Model updates", "Data drift", "Concept drift"],
        "evaluation_options": ["Gold standard response dataset comparison", "LLM-as-a-judge deviation scoring"],
    },
    {
        "id": "blurred_accountability_structures",
        "name": "Blurred Accountability Structures",
        "domain": "accountability",
        "principle": "Ownership",
        "sub_dimension": "Accountable",
        "root_causes": [
            "Insufficient human escalation triggers",
            "Unclear ownership of automated decisions",
            "Missing audit trail for automated actions",
        ],
        "evaluation_options": ["Human gating checks", "Audit trail verification", "Escalation trigger testing"],
    },
    {
        "id": "memory_rot",
        "name": "Memory Rot",
        "domain": "accountability",
        "principle": "Predictable",
        "sub_dimension": "Predictable",
        "root_causes": [
            "Unfiltered user input",
            "Data pipeline errors",
            "Improper memory decay and pruning mechanisms",
            "Lack of verification",
            "Malicious data injection",
        ],
        "evaluation_options": ["Long horizon recall tests", "False memory injection and detection"],
    },
    # ── Human Factors ─────────────────────────────────────────────────────
    {
        "id": "over_under_reliance_human_oversight",
        "name": "Over/Under-Reliance & Human Oversight",
        "domain": "human_factors",
        "principle": "Human",
        "sub_dimension": "Human",
        "root_causes": [
            "Insufficient confidence indicators in outputs",
            "Missing uncertainty flags",
            "Lack of user education on system limitations",
            "Poorly calibrated human-AI trust",
        ],
        "evaluation_options": ["Confidence indicator review", "Uncertainty flag presence", "User education assessment"],
    },
    {
        "id": "human_misuse",
        "name": "Human Misuse",
        "domain": "human_factors",
        "principle": "Responsible Accountability",
        "sub_dimension": "Accountable",
        "root_causes": [
            "Insufficient input policy enforcement",
            "Overly permissive guard node configuration",
            "Users circumventing intended use restrictions",
        ],
        "evaluation_options": ["Guard node policy review", "Input restriction testing"],
    },
    {
        "id": "human_skill_degradation",
        "name": "Human Skill Degradation (Agency & Job Displacement)",
        "domain": "human_factors",
        "principle": "Common / Social Good",
        "sub_dimension": "Social Good",
        "root_causes": [
            "Automation displacing human judgment without adequate oversight mechanisms",
            "Skills atrophy from over-reliance on system outputs",
            "Inadequate change management",
        ],
        "evaluation_options": ["Human-in-the-loop mechanism review", "Oversight adequacy assessment"],
    },
    {
        "id": "undefined_negative_value",
        "name": "Undefined or Negative Value",
        "domain": "human_factors",
        "principle": "Value Adding",
        "sub_dimension": "Value Adding",
        "root_causes": [
            "Misaligned success metrics",
            "Excessive API calls from inefficient orchestration",
            "Poorly scoped use case",
            "High latency relative to manual baseline",
        ],
        "evaluation_options": ["Cost per workflow run tracking", "Time-to-insight vs manual baseline", "User utility ratings"],
    },
]

DOMAIN_GROUPS: dict[str, list[str]] = {
    "security": [
        "agent_hijacking_prompt_injection",
        "tool_misuse_confused_deputy",
        "data_leakage",
        "model_extraction_evasion_attacks",
        "memory_data_poisoning",
    ],
    "reliability": [
        "system_instability",
        "silent_failures",
        "cascading_errors",
        "endless_cycles_looping",
        "role_specification_drift",
        "reasoning_action_mismatch",
    ],
    "transparency_fairness": [
        "algorithmic_bias",
        "obscure_logic_black_box",
        "context_rot",
        "goal_misalignment",
    ],
    "accountability": [
        "unapproved_self_improvements",
        "blurred_accountability_structures",
        "memory_rot",
    ],
    "human_factors": [
        "over_under_reliance_human_oversight",
        "human_misuse",
        "human_skill_degradation",
        "undefined_negative_value",
    ],
}

DOMAIN_DISPLAY_NAMES: dict[str, str] = {
    "security": "Security",
    "reliability": "Reliability",
    "transparency_fairness": "Transparency & Fairness",
    "accountability": "Accountability",
    "human_factors": "Human Factors",
}

RISK_BY_ID: dict[str, dict[str, Any]] = {r["id"]: r for r in RISKS}
