import hashlib
import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles

PROJECT_ROOT = Path(__file__).parent.parent
REPORTS_DIR = Path(__file__).parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)
STATIC_DIR = Path(__file__).parent / "static"

app = FastAPI(title="Trust Swarm")


# ── Report helpers ────────────────────────────────────────────────────────────

def _meta(data: dict) -> dict:
    return {
        "id": data["id"],
        "repo": data.get("repo") or data.get("trust_brief", {}).get("repo", "unknown"),
        "url": data.get("url", ""),
        "timestamp": data.get("timestamp", ""),
        "verdict": data.get("overall_verdict") or data.get("holistic", {}).get("overall_verdict", "?"),
    }


@app.on_event("startup")
def import_existing_reports() -> None:
    """Import any reports generated by the CLI into web/reports/ so they appear in history."""
    outputs_dir = PROJECT_ROOT / "outputs"
    if not outputs_dir.exists():
        return
    for json_path in sorted(outputs_dir.rglob("trust_report.json")):
        try:
            raw = json.loads(json_path.read_text())
            file_id = hashlib.md5(str(json_path).encode()).hexdigest()[:16]
            dest = REPORTS_DIR / f"{file_id}.json"
            if dest.exists():
                continue
            repo = raw.get("trust_brief", {}).get("repo") or json_path.parent.name
            verdict = raw.get("overall_verdict") or raw.get("holistic", {}).get("overall_verdict", "?")
            raw.update({
                "id": file_id,
                "url": f"https://github.com/{repo}",
                "timestamp": datetime.fromtimestamp(json_path.stat().st_mtime, tz=timezone.utc).isoformat(),
                "repo": repo,
                "overall_verdict": verdict,
            })
            dest.write_text(json.dumps(raw, indent=2))
        except Exception as exc:
            print(f"[web] Skipped {json_path}: {exc}", file=sys.stderr)


# ── API endpoints ─────────────────────────────────────────────────────────────

@app.get("/api/reports")
def list_reports() -> list[dict]:
    reports = []
    for f in sorted(REPORTS_DIR.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True):
        try:
            reports.append(_meta(json.loads(f.read_text())))
        except Exception:
            pass
    return reports


@app.get("/api/reports/{report_id}")
def get_report(report_id: str) -> dict:
    safe_id = "".join(c for c in report_id if c.isalnum() or c == "-")
    path = REPORTS_DIR / f"{safe_id}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail="Report not found")
    return json.loads(path.read_text())


@app.get("/api/run")
async def run_analysis(url: str) -> StreamingResponse:
    async def generate():
        run_id = str(uuid.uuid4())
        tmpdir = REPORTS_DIR / f"tmp_{run_id}"
        tmpdir.mkdir(exist_ok=True)

        env = os.environ.copy()
        env["PYTHONPATH"] = str(PROJECT_ROOT)

        stdout_fh = open(str(tmpdir / "report.md"), "w")
        try:
            proc = await __import__("asyncio").create_subprocess_exec(
                sys.executable, "-m", "trust_swarm", url,
                stdout=stdout_fh,
                stderr=__import__("asyncio").subprocess.PIPE,
                cwd=str(tmpdir),
                env=env,
            )
            stdout_fh.close()

            async for raw in proc.stderr:
                line = raw.decode(errors="replace").strip()
                if line:
                    yield f"event: progress\ndata: {json.dumps(line)}\n\n"

            await proc.wait()

            if proc.returncode != 0:
                yield f"event: analysis_error\ndata: {json.dumps('Analysis failed — check server logs')}\n\n"
                return

            json_path = tmpdir / "trust_report.json"
            if not json_path.exists():
                yield f"event: analysis_error\ndata: {json.dumps('Report file not found')}\n\n"
                return

            data = json.loads(json_path.read_text())
            repo = data.get("trust_brief", {}).get("repo", url)
            data.update({
                "id": run_id,
                "url": url,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "repo": repo,
            })
            (REPORTS_DIR / f"{run_id}.json").write_text(json.dumps(data, indent=2))

        except Exception as exc:
            yield f"event: analysis_error\ndata: {json.dumps(str(exc))}\n\n"
            return
        finally:
            import shutil
            shutil.rmtree(tmpdir, ignore_errors=True)

        yield f"event: complete\ndata: {json.dumps({'id': run_id})}\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


app.mount("/", StaticFiles(directory=str(STATIC_DIR), html=True), name="static")
